[CmdletBinding()]
param(
    [string] $ManifestPath = 'manifests/runtime/dependencies-v0.27.1-windows-x86_64.json',
    [string] $AcceptedPython = ''
)
Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repoRoot=Split-Path -Parent $PSScriptRoot
. (Join-Path $repoRoot 'scripts\common.ps1')

$manifestResolved=Resolve-ProjectPath -Path $ManifestPath -BasePath $repoRoot
if(-not(Test-Path -LiteralPath $manifestResolved -PathType Leaf)){throw "Dependency manifest not found: $manifestResolved"}
$manifest=Get-Content -LiteralPath $manifestResolved -Raw|ConvertFrom-Json
if([string]$manifest.component -ne 'runtime-dependencies' -or [string]$manifest.platform -ne 'windows-x86_64'){throw 'Unexpected dependency manifest identity.'}

function Get-ManifestPackageMap {
    param([Parameter(Mandatory)]$Object)
    $map=@{}
    foreach($property in $Object.PSObject.Properties){$map[[string]$property.Name]=[string]$property.Value}
    return $map
}
function Assert-PinnedFile {
    param([Parameter(Mandatory)]$Descriptor,[Parameter(Mandatory)][string]$Label)
    $relative=Assert-VllmSafeRelativePath -RelativePath ([string]$Descriptor.path) -Label "$Label path"
    $full=Join-Path $repoRoot $relative
    if(-not(Test-Path -LiteralPath $full -PathType Leaf)){throw "$Label file missing: $full"}
    $item=Get-Item -LiteralPath $full
    if($item.Length -ne [int64]$Descriptor.size_bytes){throw "$Label size mismatch. Expected $($Descriptor.size_bytes), got $($item.Length)."}
    if (($Descriptor.PSObject.Properties.Name -contains 'eol') -and [string]$Descriptor.eol -eq 'lf') {
        $bytes=[IO.File]::ReadAllBytes($full)
        if($bytes -contains [byte]13){throw "$Label must use canonical LF line endings: $full"}
    }
    $hash=Get-FileSha256 -Path $full
    if($hash -ne ([string]$Descriptor.sha256).ToUpperInvariant()){throw "$Label SHA-256 mismatch. Expected $($Descriptor.sha256), got $hash."}
    return $full
}

$inputPath=Assert-PinnedFile -Descriptor $manifest.input -Label 'Dependency input'
$lockPath=Assert-PinnedFile -Descriptor $manifest.lock -Label 'Dependency lock'
$inputLines=@(Get-Content -LiteralPath $inputPath|Where-Object{-not[string]::IsNullOrWhiteSpace($_)-and-not $_.TrimStart().StartsWith('#')})
$expectedInput=@($manifest.direct_requirements|ForEach-Object{[string]$_})
if($inputLines.Count -ne $expectedInput.Count){throw "Direct requirement count mismatch. Expected $($expectedInput.Count), got $($inputLines.Count)."}
for($i=0;$i -lt $expectedInput.Count;$i++){if($inputLines[$i] -ne $expectedInput[$i]){throw "Direct requirement mismatch at line $($i+1). Expected '$($expectedInput[$i])', got '$($inputLines[$i])'."}}

$lockLines=@(Get-Content -LiteralPath $lockPath)
$expectedHeader=@(
    '# This file was autogenerated by uv via the following command:',
    '#    uv pip compile .\runtime-v0.27.1.in --output-file .\runtime-v0.27.1.lock.txt --generate-hashes --python-platform x86_64-pc-windows-msvc --no-config'
)
if($lockLines.Count -lt 3 -or $lockLines[0] -ne $expectedHeader[0] -or $lockLines[1] -ne $expectedHeader[1]){throw 'Dependency lock generator header drifted.'}
$accepted=Get-ManifestPackageMap -Object $manifest.accepted_packages
$allowedExtras=@{}
foreach($item in @($manifest.allowed_extra_distributions)){
    $normalized=([string]$item).ToLowerInvariant().Replace('_','-')
    if([string]::IsNullOrWhiteSpace($normalized)){throw 'Allowed extra distribution name may not be empty.'}
    if($accepted.ContainsKey($normalized)){throw "Allowed extra distribution duplicates accepted dependency: $normalized"}
    if($allowedExtras.ContainsKey($normalized)){throw "Duplicate allowed extra distribution: $normalized"}
    $allowedExtras[$normalized]=$true
}
$locked=@{}
$blocks=@{}
$currentName=$null
$current=@()
function Save-LockBlock {
    if($null -eq $script:currentName){return}
    if($script:blocks.ContainsKey($script:currentName)){throw "Duplicate lock package: $script:currentName"}
    $script:blocks[$script:currentName]=@($script:current)
}
foreach($line in $lockLines){
    if($line -match '^([A-Za-z0-9_.-]+)==([^ \\]+)\s*\\?$'){
        Save-LockBlock
        $currentName=$matches[1].ToLowerInvariant().Replace('_','-')
        $current=@($line)
        $locked[$currentName]=$matches[2]
        continue
    }
    if($line -match '^([A-Za-z0-9_.-]+)\s+@\s+(\S+)\s*\\?$'){
        Save-LockBlock
        $currentName=$matches[1].ToLowerInvariant().Replace('_','-')
        $current=@($line)
        if(-not $accepted.ContainsKey($currentName)){throw "Direct URL package is not in accepted set: $currentName"}
        $locked[$currentName]=$accepted[$currentName]
        continue
    }
    if($null -ne $currentName){$current+=,$line}
}
Save-LockBlock
if($locked.Count -ne [int]$manifest.lock.package_count){throw "Locked package count mismatch. Expected $($manifest.lock.package_count), got $($locked.Count)."}
foreach($name in $locked.Keys){
    $hashLines=@($blocks[$name]|Where-Object{$_ -match '--hash=sha256:[0-9a-fA-F]{64}'})
    if($hashLines.Count -eq 0){throw "Locked package has no SHA-256 hash: $name"}
}
if($accepted.Count -ne $locked.Count){throw "Accepted package count $($accepted.Count) does not match lock count $($locked.Count)."}
$delta=@()
foreach($name in @($accepted.Keys+$locked.Keys|Sort-Object -Unique)){
    if(-not $accepted.ContainsKey($name)-or-not $locked.ContainsKey($name)-or $accepted[$name] -ne $locked[$name]){
        $delta+=($name+': accepted='+$accepted[$name]+' lock='+$locked[$name])
    }
}
if($delta.Count){throw "Dependency version drift: $($delta -join '; ')"}

$lockText=Get-Content -LiteralPath $lockPath -Raw
foreach($artifactProperty in $manifest.accepted_binary_artifacts.PSObject.Properties){
    $name=[string]$artifactProperty.Name
    $artifact=$artifactProperty.Value
    $hash=([string]$artifact.sha256).ToLowerInvariant()
    if($artifact.PSObject.Properties.Name -contains 'package_version'){
        if(-not $accepted.ContainsKey($name) -or [string]$accepted[$name] -ne [string]$artifact.package_version){throw "Accepted binary artifact package version disagrees with accepted package map: $name"}
    }
    if($lockText.IndexOf('--hash=sha256:'+$hash,[StringComparison]::OrdinalIgnoreCase) -lt 0){throw "Accepted binary artifact hash is absent from lock: $name $hash"}
    if($artifact.PSObject.Properties.Name -contains 'url'){
        $direct=[string]$artifact.url+'#sha256='+$hash
        if($lockText.IndexOf($name+' @ '+$direct,[StringComparison]::OrdinalIgnoreCase) -lt 0){throw "Accepted direct artifact URL/hash is absent from lock: $name"}
    }
}
$uvManifest=Get-Content -LiteralPath (Join-Path $repoRoot 'manifests\bootstrap\uv-0.12.13-windows-x86_64.json') -Raw|ConvertFrom-Json
$pythonManifest=Get-Content -LiteralPath (Join-Path $repoRoot 'manifests\bootstrap\cpython-3.13.15-windows-x86_64.json') -Raw|ConvertFrom-Json
if([string]$manifest.generator.version -ne [string]$uvManifest.version -or [string]$manifest.generator.commit -ne [string]$uvManifest.release.commit){throw 'Dependency lock generator uv pin disagrees with portable uv manifest.'}
if([string]$manifest.python_version -ne [string]$pythonManifest.version){throw 'Dependency lock Python pin disagrees with portable Python manifest.'}

if(-not[string]::IsNullOrWhiteSpace($AcceptedPython)){
    $pythonResolved=[IO.Path]::GetFullPath($AcceptedPython)
    if(-not(Test-Path -LiteralPath $pythonResolved -PathType Leaf)){throw "Accepted Python not found: $pythonResolved"}
    $rows=@(& $pythonResolved -I -c "import importlib.metadata as m; print('\n'.join(sorted((d.metadata['Name'].lower().replace('_','-')+'=='+d.version) for d in m.distributions() if d.metadata.get('Name'))))")
    if($LASTEXITCODE -ne 0){throw "Accepted environment metadata probe failed (exit $LASTEXITCODE)."}
    $environment=@{}
    foreach($row in $rows){
        if([string]::IsNullOrWhiteSpace($row)){continue}
        $parts=$row.Split(@('=='),2,[StringSplitOptions]::None)
        if($parts.Count -ne 2){throw "Unexpected accepted environment row: $row"}
        $environment[$parts[0]]=$parts[1]
    }
    $environmentDelta=@()
    foreach($name in @($accepted.Keys|Sort-Object)){
        if(-not $environment.ContainsKey($name) -or $accepted[$name] -ne $environment[$name]){
            $actual=if($environment.ContainsKey($name)){$environment[$name]}else{'<missing>'}
            $environmentDelta+=($name+': manifest='+$accepted[$name]+' environment='+$actual)
        }
    }
    foreach($name in @($environment.Keys|Sort-Object)){
        if(-not $accepted.ContainsKey($name) -and -not $allowedExtras.ContainsKey($name)){
            $environmentDelta+=($name+': unexpected environment distribution='+$environment[$name])
        }
    }
    if($environmentDelta.Count){throw "Accepted environment drift: $($environmentDelta -join '; ')"}
    Write-Host 'ACCEPTED_ENVIRONMENT_28_OF_28_OK'
}
Write-Host 'RUNTIME_DEPENDENCY_LOCK_OK'
